version: "3.9"
services:
  web:
    build: ./
    command: python main.py
    volumes:
      - ./:/usr/src/app/
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
